# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
<<<<<<< HEAD
<<<<<<< HEAD
  
=======
>>>>>>> 55d1546a4d2fac20c0efa817002050700e3b82c5
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'source/repos/CUSTOMERAPISQL/CUSTOMERAPISQL.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
<<<<<<< HEAD
  displayName: 'publish artifacts'
=======
  displayName: 'publish artifacts'
>>>>>>> 55d1546a4d2fac20c0efa817002050700e3b82c5
=======
>>>>>>> ea95ccd34c29e21baee526626aa72a325beb338d
